name: Basic workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  basic-job:
    runs-on: ubuntu-latest
    steps:
      - name: Hello world
        run: echo "Hello, world!"
